import { formatIndianDate } from './constants';

// Demo Users
export const demoUsers = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@example.com',
    role: 'citizen',
    aadhaar: 'XXXX-XXXX-1234',
    phone: '+91 98765 43210',
    address: 'H.No. 4-5-123, Dilsukhnagar, Hyderabad',
    state: 'TS',
    district: 'Hyderabad',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya.sharma@gov.in',
    role: 'officer',
    department: 'Revenue Department',
    designation: 'Tahsildar',
    district: 'Rangareddy',
  },
  {
    id: '3',
    name: 'Admin User',
    email: 'admin@landrevenue.gov.in',
    role: 'admin',
    department: 'IT Administration',
  },
];

// Demo Land Parcels
export const demoLandParcels = [
  {
    id: 'LP001',
    surveyNumber: '123',
    subDivision: 'A',
    village: 'Shamshabad',
    taluk: 'Shamshabad',
    district: 'Rangareddy',
    state: 'Telangana',
    ownerName: 'Rajesh Kumar',
    ownerAadhaar: 'XXXX-XXXX-1234',
    fatherName: 'Late Shri Ramesh Kumar',
    landType: 'Agricultural',
    totalArea: 2.5,
    areaUnit: 'Acres',
    marketValue: 15000000,
    registrationDate: '15-03-2018',
    khataNumber: 'KH-2018-00456',
    pattaNumber: 'PT-RR-2018-789',
    boundaries: {
      north: 'Survey No. 124 - Suresh Reddy',
      south: 'Village Road',
      east: 'Survey No. 122 - Government Land',
      west: 'Survey No. 125 - Venkat Rao',
    },
    documents: [
      { id: 'd1', name: 'Sale Deed', type: 'pdf', uploadedOn: '15-03-2018' },
      { id: 'd2', name: 'Encumbrance Certificate', type: 'pdf', uploadedOn: '20-03-2018' },
      { id: 'd3', name: 'Patta Copy', type: 'pdf', uploadedOn: '25-03-2018' },
    ],
    taxDue: 12500,
    lastTaxPaid: '01-04-2023',
  },
  {
    id: 'LP002',
    surveyNumber: '456',
    subDivision: 'B1',
    village: 'Ibrahimpatnam',
    taluk: 'Ibrahimpatnam',
    district: 'Rangareddy',
    state: 'Telangana',
    ownerName: 'Rajesh Kumar',
    ownerAadhaar: 'XXXX-XXXX-1234',
    fatherName: 'Late Shri Ramesh Kumar',
    landType: 'Residential',
    totalArea: 0.5,
    areaUnit: 'Acres',
    marketValue: 8500000,
    registrationDate: '22-07-2020',
    khataNumber: 'KH-2020-00892',
    pattaNumber: 'PT-RR-2020-345',
    boundaries: {
      north: 'Survey No. 457 - Municipal Park',
      south: 'Main Road NH-65',
      east: 'Survey No. 455 - Lakshmi Devi',
      west: 'Survey No. 458 - Commercial Complex',
    },
    documents: [
      { id: 'd4', name: 'Sale Deed', type: 'pdf', uploadedOn: '22-07-2020' },
      { id: 'd5', name: 'Layout Approval', type: 'pdf', uploadedOn: '25-07-2020' },
    ],
    taxDue: 0,
    lastTaxPaid: '15-06-2024',
  },
  {
    id: 'LP003',
    surveyNumber: '789',
    subDivision: '',
    village: 'Maheshwaram',
    taluk: 'Maheshwaram',
    district: 'Rangareddy',
    state: 'Telangana',
    ownerName: 'Suresh Reddy',
    ownerAadhaar: 'XXXX-XXXX-5678',
    fatherName: 'Shri Venkateshwar Reddy',
    landType: 'Commercial',
    totalArea: 1.2,
    areaUnit: 'Acres',
    marketValue: 45000000,
    registrationDate: '10-11-2019',
    khataNumber: 'KH-2019-01234',
    pattaNumber: 'PT-RR-2019-567',
    boundaries: {
      north: 'Survey No. 790 - IT Park',
      south: 'ORR Service Road',
      east: 'Survey No. 788 - Warehouse',
      west: 'Survey No. 791 - Open Land',
    },
    documents: [
      { id: 'd6', name: 'Sale Deed', type: 'pdf', uploadedOn: '10-11-2019' },
      { id: 'd7', name: 'Conversion Order', type: 'pdf', uploadedOn: '15-11-2019' },
      { id: 'd8', name: 'NOC from Revenue', type: 'pdf', uploadedOn: '20-11-2019' },
    ],
    taxDue: 35000,
    lastTaxPaid: '01-01-2024',
  },
];

// Demo Mutation Requests
export const demoMutationRequests = [
  {
    id: 'MUT001',
    applicationNumber: 'MUT-2024-001234',
    applicantName: 'Rajesh Kumar',
    applicantAadhaar: 'XXXX-XXXX-1234',
    surveyNumber: '123/A',
    village: 'Shamshabad',
    district: 'Rangareddy',
    mutationType: 'Sale',
    previousOwner: 'Venkat Rao',
    newOwner: 'Rajesh Kumar',
    applicationDate: '05-11-2024',
    status: 'under_review',
    assignedOfficer: 'Priya Sharma',
    documents: ['Sale Deed', 'Encumbrance Certificate', 'Aadhaar Copy'],
    remarks: 'Document verification in progress',
  },
  {
    id: 'MUT002',
    applicationNumber: 'MUT-2024-001189',
    applicantName: 'Lakshmi Devi',
    applicantAadhaar: 'XXXX-XXXX-9012',
    surveyNumber: '455',
    village: 'Ibrahimpatnam',
    district: 'Rangareddy',
    mutationType: 'Inheritance',
    previousOwner: 'Late Shri Ranga Rao',
    newOwner: 'Lakshmi Devi',
    applicationDate: '28-10-2024',
    status: 'pending',
    assignedOfficer: null,
    documents: ['Death Certificate', 'Legal Heir Certificate', 'Aadhaar Copy'],
    remarks: 'Awaiting officer assignment',
  },
  {
    id: 'MUT003',
    applicationNumber: 'MUT-2024-001098',
    applicantName: 'Suresh Reddy',
    applicantAadhaar: 'XXXX-XXXX-5678',
    surveyNumber: '789',
    village: 'Maheshwaram',
    district: 'Rangareddy',
    mutationType: 'Gift',
    previousOwner: 'Venkateshwar Reddy',
    newOwner: 'Suresh Reddy',
    applicationDate: '15-10-2024',
    status: 'approved',
    assignedOfficer: 'Priya Sharma',
    documents: ['Gift Deed', 'Family Tree', 'Aadhaar Copies'],
    remarks: 'Mutation completed successfully',
    completionDate: '01-11-2024',
  },
];

// Demo Tax Records
export const demoTaxRecords = [
  {
    id: 'TAX001',
    surveyNumber: '123/A',
    village: 'Shamshabad',
    ownerName: 'Rajesh Kumar',
    financialYear: '2024-25',
    baseTax: 10000,
    cess: 1500,
    penalty: 1000,
    totalDue: 12500,
    dueDate: '31-03-2025',
    status: 'pending',
    lastPaymentDate: '01-04-2023',
    lastPaymentAmount: 11000,
  },
  {
    id: 'TAX002',
    surveyNumber: '456/B1',
    village: 'Ibrahimpatnam',
    ownerName: 'Rajesh Kumar',
    financialYear: '2024-25',
    baseTax: 15000,
    cess: 2250,
    penalty: 0,
    totalDue: 0,
    dueDate: '31-03-2025',
    status: 'paid',
    lastPaymentDate: '15-06-2024',
    lastPaymentAmount: 17250,
  },
];

// Demo Activity Logs (for Admin)
export const demoActivityLogs = [
  {
    id: 'LOG001',
    timestamp: '08-12-2024 14:32:15',
    user: 'priya.sharma@gov.in',
    action: 'Mutation Approved',
    details: 'Approved mutation request MUT-2024-001098',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'LOG002',
    timestamp: '08-12-2024 13:15:42',
    user: 'rajesh.kumar@example.com',
    action: 'Tax Payment',
    details: 'Paid ₹17,250 for Survey No. 456/B1',
    ipAddress: '103.45.67.89',
  },
  {
    id: 'LOG003',
    timestamp: '08-12-2024 11:45:30',
    user: 'admin@landrevenue.gov.in',
    action: 'User Role Updated',
    details: 'Updated role for user ID: 5 to Officer',
    ipAddress: '10.0.0.1',
  },
];

// Demo Notifications
export const demoNotifications = [
  {
    id: 'NOT001',
    title: 'Tax Payment Due',
    message: 'Land tax for Survey No. 123/A is due by 31-03-2025',
    type: 'warning',
    date: '01-12-2024',
    read: false,
  },
  {
    id: 'NOT002',
    title: 'Mutation Application Update',
    message: 'Your mutation application MUT-2024-001234 is under review',
    type: 'info',
    date: '28-11-2024',
    read: true,
  },
  {
    id: 'NOT003',
    title: 'Document Verified',
    message: 'Sale deed for Survey No. 456/B1 has been verified',
    type: 'success',
    date: '25-11-2024',
    read: true,
  },
];
